### PR TITLE
fix(packages/vkui): add missed "type": "module"

### PR DESCRIPTION
**Pull request by inomdzhon**
- caused by #7611

---

## Описание

В #7611 у пакета `packages/vkui` мы удалили поле `"main"`, но при этом `"type"` остался как `commonjs`.

Обнаружил это при тестировании `v7.0.0-beta.1` в стороннем репозитории при запуске **Jest**. Из-за `"type": "commonjs"`, он пытается обратиться к полю `"main"`, но так как его нет, тест падает с ошибкой `Cannot find module`. С `"type": "module"` такой проблемы не будет, т.к. уже будет обращаться к полю `"module"`.

## Изменения

Это повлекло за собой следующие изменения:

- ~`packages/vkui/shared.config.js`~ – переименование в `.mjs` не удалось из-за **react-styleguidist**, который не умеет в **ESM**, поэтому перенёс содержимое в корневой `shared.js`, который используется только в папке `/styleguide`
- `stylelint.config.mjs` – заменил импорты из `shared.config.js` на объявление путей прямо в файле
- `packages/vkui/cssm/postcss.config.js` → `packages/vkui/cssm/postcss.config.cjs` – заменил импорты из `shared.config.js` на объявление путей прямо в файле
- `packages/vkui/scripts/postcss.js` → `packages/vkui/scripts/postcss.cjs` – заменил импорты из `shared.config.js` на объявление путей прямо в файле, а также перенёс объявления `VKUI_TOKENS_CSS` и `generateScopedName`
- `packages/vkui/tsconfig.json` – упростил `include`, а то было точечное определение файлов
- `packages/vkui/.eslintrc.js` → `packages/vkui/.eslintrc.cjs`, иначе падает с ошибкой **ERR_REQUIRE_ESM**. Также обнаружилось, что в `@vkontakte/vkjs` не хватает поля `"exports"` (см. https://github.com/VKCOM/vkjs/pull/552)
- `packages/vkui/rspack.styles.config.ts` → `packages/vkui/rspack.styles.config.mjs`, т.к. начал падать с ошибкой `ERR_UNKNOWN_FILE_EXTENSION`
- `packages/vkui/playwright-ct.config.ts` → `packages/vkui/playwright-ct.config.mjs`, т.к. **Playwright** хочет **ESM** синтаксис для `__dirname` и импортов **JSON**, что не соответствует нашему `tsconfig.json`, а отдельный `tsconfig.e2e.json` не завёлся. Также перенёс плагины из `scripts/postcss.cjs` прямо в конфиг, т.к. импорт `scripts/postcss.cjs` фризит запуск **Playwright**
- `packages/vkui/jest.config.ts` – добавляем `@vkontakte/vkjs` в `transformIgnorePatterns`, т.к. библиотека теперь полностью поставляется как ESM (https://github.com/VKCOM/vkjs/pull/552).

## Исправления
- В `package.json` добавлено пропущенное поле `"type": "module"`

## Зависимости
- [@vkonktate/vkjs](https://www.npmjs.com/package/@vkontakte/vkjs) обновлён с `1.3.0` до `2.0.1`

### CODE REVIEW

**Review by BlackySoul — DISMISSED** [review]

**Review by SevereCloud — APPROVED** [review]
image

**Review by BlackySoul — APPROVED** [review]

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0-beta.2" target="_blank">v7.0.0-beta.2</a> 🎉

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0" target="_blank">v7.0.0</a> 🎉
